spring.application.name=disco-prep

# PostgreSQL local lancé avec docker
spring.datasource.url=jdbc:postgresql://localhost:5432/disco_db
spring.datasource.username=disco
spring.datasource.password=disco

# JPA / Hibernate
# Validate = Hibernate vérifie que les tables existent, mais ne les crée pas
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# Port de l'application
server.port=8080